### ISSUE TITLE
add version number

### ISSUE THREAD

**Issue by radislaw** [davidgilbertson/know-it-all#12]
It would be good to add information about the version and list of changes

**Comment by davidgilbertson** [comment]
I'm not sure exactly what you're after.

There aren't really 'versions' of the site. I make a change, do a commit, deploy the site. The [list of commits is the change log](https://github.com/davidgilbertson/know-it-all/commits/master).

For testing I sometimes bump the version in `package.json` and if you hover your mouse over the title you see this version - but really this was for when I was getting the hang of service workers.

Or are you thinking of something like I did in [this site's repo](https://github.com/davidgilbertson/malla/releases) with more official releases with screenshots and the like?

**Comment by radislaw** [comment]
I meant that I would like to know if the project changed since my last visit, without having to visit github. This project is still raw and frequent changes are inevitable.

**Comment by davidgilbertson** [comment]
Ah I see. To be honest I would rank this as less important than other features for a few reasons:
- I don't think this is something the average user expects. I can't think of another app that does this.
- It adds to the UI - I'm trying to keep it minimal
