### ISSUE TITLE
error: cant find /public/firstModule.json

### ISSUE THREAD

**Issue by ivanberry** [davidgilbertson/know-it-all#15]
Hi,
After cloneing and  runnning `npm install`, and then`npm run dev`,  Say 'cant not find `/public/firstModule.json`', is anything I missing? Thanks!

**Comment by davidgilbertson** [comment]
Hi, try running `npm run build` first. I'll add this to the readme.

**Comment by ivanberry** [comment]
@davidgilbertson ，It works, Thanks sincerely! :smile:

**Comment by davidgilbertson** [comment]
Updated the readme.
