### ISSUE TITLE
Click 'know it' on parent, auto-click children.

### ISSUE THREAD

**Issue by angelod1as** [davidgilbertson/know-it-all#18]
So I've opened, let's say, CSS 2.1. The, Box Model. Then, Margin. 

Well, I know all margin parameters, so I'll just click `margin: Know it`, right? 

Wrong. I have to click **every single know it**.

It would be way nicer to click Know it on father and blam, all children 'know it' too.

**Comment by davidgilbertson** [comment]
I agonised over this particular aspect of the UX.

The reason I didn't have "Know it" propagate down is that when I went through this list, there was a lot of stuff that I didn't know where I would have thought that I new everything (even in the basics like CSS `display`). By propagating down "Know it", it becomes very easy to steamroll over something that you didn't know.

I elaborate on this [in the blog post](https://hackernoon.com/master-web-development-with-these-9-985-weird-tricks-77c71d1d96f3#.v6s88fkql).

I will be adding in propagation for the "Don't know it" and "Don't care" options. And maybe at some point in the future add a setting to allow propagation of "Know it" and "Know of it".
