### ISSUE TITLE
Know-it-all into a Printed Book.vol1,vol2,vol3..

### ISSUE THREAD

**Issue by gerald23** [davidgilbertson/know-it-all#20]
Make this into a Task Book/Work Book in paper print.It will benefit lot of students who pursue career in Web Design/Web Development.
1 new issue for me, free.
r.john Gerald
webset34@gmail.com

**Comment by davidgilbertson** [comment]
This is an interesting idea. If I was to do this I would start simply with print-friendly pages for each module, so you could print to PDF from the browser. Setting up book printing channels is an amount of work I'm not prepared to do.

However, I don't plan on implementing this.

**Comment by gerald23** [comment]
Okay.Have a Nice Day.
