### ISSUE TITLE
Arrow key functionality

### ISSUE THREAD

**Issue by numbergames** [davidgilbertson/know-it-all#23]
Submitted a PR (https://github.com/davidgilbertson/know-it-all/pull/22) to give left and right arrow keys more intuitive (subjectively) behavior. Left arrow still collapses if `selectedItem` is expanded, otherwise navigates to parent node.  Right arrow, similarly, expands current selection or navigates to first child.

Should have opened this before PR.  Love the project. Learning from your architecture and project structure.

Cheers

**Comment by davidgilbertson** [comment]
Thanks for this, I've been very slack in not looking at it yet. I'll aim to review it on Saturday.

It's much appreciated!

**Comment by davidgilbertson** [comment]
Merged
