### ISSUE TITLE
Export with multiple options feature request 

### ISSUE THREAD

**Issue by David-Else** [davidgilbertson/know-it-all#26]
This tool would be great to create a document to add to your CV to show what you know!

Having an export to multiple formats would be amazing. Being able to choose which areas to include would be even better.

I am not sure what formats would be best, but HTML would be very flexible, then you could edit and style it how you like. Maybe that would be a minority use case, as most people would probably prefer PDF for ease of use.

THANKS for this awesome tool!

**Comment by davidgilbertson** [comment]
Thanks, I like the idea. I think allowing users to take their data is the right thing to do generally, so I would at least do this as `JSON`. Other than that, `CSV` is probably the most portable raw format.

For now I'll add this to the TODO list, but no idea when I'll get to it.

Pull requests are always welcome ;)
