### ISSUE TITLE
Bandwidth Quota Exceeded

### ISSUE THREAD

**Issue by ghost** [davidgilbertson/know-it-all#44]
When loading the site, I see the following error:

**Bandwidth Quota Exceeded**
This site has exceeded its monthly quota for bandwidth. It must be upgraded via the Firebase console before it can begin serving traffic again.

I attach this image for reference.
![screen shot 2018-11-28 at 7 13 06 pm](https://user-images.githubusercontent.com/42884109/49155779-cfd3fb00-f341-11e8-952e-3297ee6bb3aa.png)

**Comment by davidgilbertson** [comment]
Yep I noticed. Someone attacked the site and downloaded 667.7 GB a few days ago which put me over my quota. No one uses the site so I'm just going to leave it.

Thanks for reporting but I'll close this.
