### ISSUE TITLE
List Icons Visibility

### ISSUE THREAD

**Issue by TycoT** [davidgilbertson/know-it-all#6]
Its hard to distinguish between the dropdowns arrows and bullet points from a quick glance, I think it would be better visibility if the icons were filled in or perhaps have a darker outline. 

Heres an example of what I see:
![screen shot 2017-01-08 at 10 05 02 am](https://cloud.githubusercontent.com/assets/8959583/21750479/12c52eac-d58a-11e6-96f9-926b4527deab.png)

**Comment by pangolingo** [comment]
I agree. I didn't even notice the icons because of my screen brightness, and it took me a long time to realize that I could expand rows.

**Comment by davidgilbertson** [comment]
Yep that's appalling, will fix shortly. Thanks for reporting!

**Comment by davidgilbertson** [comment]
Fixed

![bs_realios_mobile_iphone 6s plus-9 0 1](https://cloud.githubusercontent.com/assets/4443482/21758509/ae746028-d690-11e6-8c9f-a03b3ae0602f.jpg)

**Comment by TycoT** [comment]
Nice! 👍
