### ISSUE TITLE
Last row is not visible in mobile browsers

### ISSUE THREAD

**Issue by jozsefs** [davidgilbertson/know-it-all#7]
On mobile phones the last row is not visible when the 4 buttons are shown at the bottom.
You can't scroll to them because the page height stays the same.
Tested with iPhone 6S chrome/safari.
Testable with chrome device debugger (iPhone 6 for example or Nexus 5).

![capture](https://cloud.githubusercontent.com/assets/3122514/21750967/820360ec-d5bf-11e6-8aa5-61e655891b1e.JPG)

**Comment by davidgilbertson** [comment]
D'oh. I'll fix that shortly. Thanks for reporting!

**Comment by davidgilbertson** [comment]
In addition to this bug, the behaviour was pretty crappy on Safari which hijacks click events near the bottom for its own purposes. So I've moved the score bar to the top. Not super happy with that but I can't think of a better solution. 

![image](https://cloud.githubusercontent.com/assets/4443482/21760050/2d70ea84-d69d-11e6-92df-027bf8d1ec66.png)
