### ISSUE TITLE
Unselect option

### ISSUE THREAD

**Issue by gxxaxx** [davidgilbertson/know-it-all#9]
Given the existence of sub-items it would be good to provide un-select for the summary lines.
Otherwise one is forced to use "Don't Care" in order to back-off on items that have sub-items one does not know. Or simply provide a button for "Unrated"

**Comment by davidgilbertson** [comment]
#10 may go some way towards solving this. But what I'm thinking is that each button is an on/off toggle.

**Comment by davidgilbertson** [comment]
Thanks for the feedback!

Should be fixed by https://github.com/davidgilbertson/know-it-all/commit/9dc30768f4d5d677b5e993e2c34470edab73aee8

Clicking a button now toggles the score.
